images:
  compatlink: ghcr.io/guild-link/compatlink@sha256:2e02b71aa4f3781f1053e1f6580d49d8d146b23594e2c0777ddd4076cd381178
  cf-router: ghcr.io/guild-link/cf-router@sha256:b03259638788421f93b3008cdd88f4e2227e3e65f177dc1f43c2b49d3f72b9ad
  backend: ghcr.io/guild-link/backend@sha256:b87cbf1eca4113daca6b046e0131f27145af7726e868cb2c17983325a6287aa0
  worker: ghcr.io/guild-link/worker@sha256:abf9a5cc7074964c0240c738575c59fb643a5fc83ed4239f0e2729c09a5a6284
  valkey: valkey/valkey:latest
ports:
  compatlink: 80
  hypixel-router: 25565
  valkey: 6379
replicas:
  compatlink: 1
  hypixel-router: 1
resources:
  compatlink:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
  hypixel-router:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      memory: 64Mi
  valkey:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 512Mi
